language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install codecov
  - pip install -r requirements.txt

script:
  - python setup.py install
  - coverage run tests/test_entropy.py

after_success:
  - codecov